const subreddits = [
  "google_antigravity",
  "AskReddit",
  "NoStupidQuestions",
  "BaldursGate3",
  "facepalm",
  "interestingasfuck",
  "Damnthatsinteresting",
  "LivestreamFail",
  "pics",
  "Palworld",
  "AmItheAsshole",
  "mildlyinfuriating",
  "Piracy",
  "PeterExplainsTheJoke",
  "funny",
  "AITAH",
  "movies",
  "Helldivers",
  "gaming",
  "worldnews",
  "leagueoflegends",
  "pcmasterrace",
  "Unexpected",
  "news",
  "politics",
];

export default subreddits;
